## Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
#import numpy
import numpy as np

In [2]:
#Function  using numpy.column_stack() function
def generateVanderMatrix(inputVector,N):
    x = np.array(inputVector)
    #Matrix when N is defined 
    if(N!=None):
        # increasing order is False
        y = np.column_stack([x**[N-i-1] for i in range(N)])
        print('Vander Matrix when increasing order is False ')
        print(y)
        print('------------------------------------------------')
        # increasing order is True
        print('Vander Matrix when increasing order is True ')
        z = np.column_stack([x**[N-i-1] for i in range(N)])
        print(np.flip(z,axis=1))
    # when N is not defined , the square matrix will be produced from the length of the vector
    else:
         # increasing order is False
        y = np.column_stack([x**[len(x)-i-1] for i in range(len(x))])
        print('Vander Matrix when increasing order is False ')
        print(y)
        print('------------------------------------------------')
        # increasing order is True
        z = np.column_stack([x**[len(x)-i-1] for i in range(len(x))])
        print('Vander Matrix when increasing order is True ')
        print(np.flip(z,axis=1)) 

In [3]:
generateVanderMatrix([1,2,3,5],None)

Vander Matrix when increasing order is False 
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
------------------------------------------------
Vander Matrix when increasing order is True 
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


In [4]:
generateVanderMatrix([1,2,3,5],3)

Vander Matrix when increasing order is False 
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
------------------------------------------------
Vander Matrix when increasing order is True 
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]


In [5]:
generateVanderMatrix([1,2,3,4,5,6],None)

Vander Matrix when increasing order is False 
[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]
------------------------------------------------
Vander Matrix when increasing order is True 
[[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]
 [   1    6   36  216 1296 7776]]


In [6]:
generateVanderMatrix([1,2,3,4,5,6],5)

Vander Matrix when increasing order is False 
[[   1    1    1    1    1]
 [  16    8    4    2    1]
 [  81   27    9    3    1]
 [ 256   64   16    4    1]
 [ 625  125   25    5    1]
 [1296  216   36    6    1]]
------------------------------------------------
Vander Matrix when increasing order is True 
[[   1    1    1    1    1]
 [   1    2    4    8   16]
 [   1    3    9   27   81]
 [   1    4   16   64  256]
 [   1    5   25  125  625]
 [   1    6   36  216 1296]]


In [7]:
#Function using numpy.vander() function
def generateVanderMatrix1(inputVector,N):
    x = np.array(inputVector)
     #Matrix when N is defined 
    if(N!=None):
        # increasing order is False
        y = np.vander(x, N, increasing=False)
        print('Vander Matrix when increasing order is False ')
        print(y)
        print('------------------------------------------------')
        # increasing order is True
        print('Vander Matrix when increasing order is True ')
        z = np.vander(x,N,increasing=True)
        print(z)
    # when N is not defined , the square matrix will be produced from the length of the vector
    else:
         # increasing order is False
        y = np.vander(x, N, increasing=False)
        print('Vander Matrix when increasing order is False ')
        print(y)
        print('------------------------------------------------')
        # increasing order is True
        z = np.vander(x,N,increasing=True)
        print('Vander Matrix when increasing order is True ')
        print(np.flip(z,axis=1)) 

In [8]:
generateVanderMatrix1([1,2,3,5],None)

Vander Matrix when increasing order is False 
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
------------------------------------------------
Vander Matrix when increasing order is True 
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [9]:
generateVanderMatrix1([1,2,3,5],3)

Vander Matrix when increasing order is False 
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
------------------------------------------------
Vander Matrix when increasing order is True 
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]


In [10]:
generateVanderMatrix1([1,2,3,4,5,6],None)

Vander Matrix when increasing order is False 
[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]
------------------------------------------------
Vander Matrix when increasing order is True 
[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]


In [11]:
generateVanderMatrix1([1,2,3,4,5,6],5)

Vander Matrix when increasing order is False 
[[   1    1    1    1    1]
 [  16    8    4    2    1]
 [  81   27    9    3    1]
 [ 256   64   16    4    1]
 [ 625  125   25    5    1]
 [1296  216   36    6    1]]
------------------------------------------------
Vander Matrix when increasing order is True 
[[   1    1    1    1    1]
 [   1    2    4    8   16]
 [   1    3    9   27   81]
 [   1    4   16   64  256]
 [   1    5   25  125  625]
 [   1    6   36  216 1296]]
